### ISSUE TITLE
 Crash Game

### ISSUE THREAD

**Issue by ManzyFun** [IMB11/SkinShuffle#100]
### Crash the game

When I click on Skin Presets the game crashes. The “Save the World” icon pops up (When I didn’t even enter the world) and then Minecraft closes. An error is displayed in the launcher. 
The same thing happens in a neglected world, only without the inscription “Save the world”
The error : The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Rendering entity in world

### Relevant log output

_https://mclo.gs/nabCVLm_

### SkinShuffle version

2.1.0+1.21

**Comment by IMB11** [comment]
Please remove your mods one by one until the crash no longer occurs.

**Comment by ManzyFun** [comment]
I removed all mods except Fabric API and SkinShuffle itself. Same error

**Comment by Rozbiynk** [comment]
same error, do you updating from previous version?

**Comment by ManzyFun** [comment]
I get this error on different versions.

**Comment by IMB11** [comment]
This might be fixed in the latest version, have you tried the latest version of SkinShuffle?

**Comment by IMB11** [comment]
I will consider using a non entity based renderer for skins in the next update, for some reason it just... dies on Windows devices.

**Comment by Rozbiynk** [comment]
last time i've seen something like that was bobby incompatibility, but that time i even cant add skin

**Comment by IMB11** [comment]
Should be fixed with 2.2.0's release. Please re-open if you still encounter this after 2.2.0 releases.

**Comment by ManzyFun** [comment]
game still crashes when I click "Skin Presets". But now a new error has appeared: The game crashed while rendering screen
Error: java.lang.NullPointerException: Rendering screen.

**Comment by IMB11** [comment]
Open a new issue
