### ISSUE TITLE
Game crashes when i press on skin presets

### ISSUE THREAD

**Issue by HotCatpolska** [IMB11/SkinShuffle#102]
### Describe the issue

when i press on "skin presets" the game sayes " saving world" and then it crashes with the error message "The game crashed whilst endering  entity in world 
Error:java.lang.NullPointerException: Rendering enitiy in world"

### SkinShuffle version

game version 1.21 mod version 2.1.0

### Extra information

i have these mods:
![Bild_2024-08-14_223432544](https://github.com/user-attachments/assets/998080d7-754c-442e-bbe2-8a663c391065)

**Comment by Urobi96** [comment]
I have the same problem

**Comment by IMB11** [comment]
Should be fixed with 2.2.0's release. Please re-open if you still encounter this after 2.2.0 releases.

**Comment by HotCatpolska** [comment]
still doesnt work 
![image](https://github.com/user-attachments/assets/7416ecf5-b155-40d8-a318-6f4a6157e73e)

**Comment by IMB11** [comment]
Please upload your logs to mclo.gs

**Comment by Rozbiynk** [comment]
https://mclo.gs/TIl5DJ3

**Comment by Rozbiynk** [comment]
https://mclo.gs/ShwBNDG crash report
