### ISSUE TITLE
Crash game

### ISSUE THREAD

**Issue by ManzyFun** [IMB11/SkinShuffle#106]
### Describe the issue

К сожалению, игра все еще вылетает, когда я нажимаю «Skin Presets». Но теперь появилась новая ошибка: Игра вылетела во время рендеринга экрана
Ошибка: java.lang.NullPointerException: Rendering screen.

### Relevant log output

https://mclo.gs/zflKiap

### SkinShuffle version

2.2.1+1.21

**Comment by IMB11** [comment]
Delete your skinshuffle folder and restart the game.

**Comment by ManzyFun** [comment]
THANK YOU SO MUCH, YOU WERE HELPING VERY MUCH!!!!!!!!!!!!
