### ISSUE TITLE
Incompatible mod

### ISSUE THREAD

**Issue by ManzyFun** [IMB11/SkinShuffle#108]
### Describe the issue

I’m about to launch Minecraft on version 1.20 and suddenly an error appears that an incompatible mod has been detected: “YetAnotherConfigLib (v3)”, although I don’t have this mod. I checked all the mods and the error did not occur, except for 1 mod: "SkinShuffle". In general, Fabric is asking me to replace the mod version "YetAnotherConfigLib" 3.5.0+1.21.1 with version 3.5.0+1.21.1 or later, compatible with 1.20. But I was confused by the fact that they were asking me to replace it with the same version (3.5.0+1.21.1), oh well, probably a bug. In general, I am asking for your help to fix this.

### SkinShuffle version

2.2.1+1.20.1

**Comment by IMB11** [comment]
Please upload your logs to https://mclo.gs/

**Comment by ManzyFun** [comment]
Um, but there are no logs. Writes: “The game crashed due to an unexpected error. We apologize for the inconvenience.
Completion code: 1"

**Comment by IMB11** [comment]
Click "Open Crash Report", copy the text and paste it into the https://mclo.gs/ upload box.

**Comment by ManzyFun** [comment]
I only have "Copy error code" and "Close"

**Comment by IMB11** [comment]
Oh - make sure you install the correct "Yet Another Config Lib" version for the game version you are using. You need to download YACL 3.5.0+1.20.1+fabric
