### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by FAMJAM1** [IMB11/SkinShuffle#109]
### Describe the issue

Crash while entering the game

### Relevant log output

https://mclo.gs/dSmjrWV

### SkinShuffle version

2.2.1+1.21

### Extra information

Win 11

**Comment by IMB11** [comment]
Delete your `.minecraft/config/skinshuffle` folder and restart the game.

**Comment by FAMJAM1** [comment]
Thanks, everything works now, except now the “Display Widget In Title Screen” button doesn't work, but the “Display Widget In Pause Screen” works.

**Comment by IMB11** [comment]
Will look into it.

**Comment by zcraftelite9495** [comment]
This is due to an incompatibility with ViaFabricPlus. Same as issue #114.
