### ISSUE TITLE
ncompatible mod (again)

### ISSUE THREAD

**Issue by ManzyFun** [IMB11/SkinShuffle#112]
### Describe the issue

Uhhh, and so. After your advice, I downloaded the "YetAnotherConfigLib" mod, but version 3.5.0+1.20.1 was only for 1.20.1, when I needed it for 1.20. I downloaded the same mod for version 1.20 (3.2.2+1.20 (there was no other one, it was the latest one)) and I got the error: ### Replace mod 'YetAnotherConfigLib' (yet_another_config_lib_v3) 3.2.2+1.20 and mod 'YetAnotherConfigLib' (yet_another_config_lib_v3 ) 3.5.0+1.20.1-fabric with mod 'YetAnotherConfigLib' (yet_another_config_lib_v3), version 3.5.0+1.20.1-fabric or later. Mod 'YetAnotherConfigLib' (yet_another_config_lib_v3) 3.5.0+1.20.1-fabric requires version 1.20.1 of 'Minecraft'(minecraft), but only the wrong version is present: 1.20!
I'm like: Ok, I'll download the "YetAnotherConfigLib" 1.20.1 mod (what I was told). So I downloaded it and I get the error again: ### Replace mod 'YetAnotherConfigLib' (yet_another_config_lib_v3) 3.5.0+1.20.1-fabric and mod 'YetAnotherConfigLib' (yet_another_config_lib_v3) 3.5.0+1.20.1-fabric with mod 'YetAnotherConfigLib' ( yet_another_config_lib_v3), version 3.5.0+1.20.1-fabric or later. Mod 'YetAnotherConfigLib' (yet_another_config_lib_v3) 3.5.0+1.20.1-fabric requires version 1.20.1 of 'Minecraft'(minecraft), but only the wrong version is present: 1.20!
And this was expected, because the mod is for version 1.20.1, and I have 1.20.
As a result, I realized that the “YetAnotherConfigLib” mod is built into the “Skin Shuffle” mod, because now I’m getting an error message from 2 identical mods. Help please!

### SkinShuffle version

2.2.1+1.20.1

### Extra information

I don’t have Logs, because it just gives me an error with the completion code “1”.

**Comment by IMB11** [comment]
1.20.1 is compatible with 1.20, use YACL 3.5.0+1.20.1
