### ISSUE TITLE
crash in 1.21

### ISSUE THREAD

**Issue by Domen-1** [IMB11/SkinShuffle#114]
### Describe the issue

when i press "create", my game is crash 
crash report below
[crash-2024-09-08_22.13.59-client.txt](https://github.com/user-attachments/files/16923288/crash-2024-09-08_22.13.59-client.txt)

### SkinShuffle version

2.2.1 + 1.21 or 2.2.2 + 1.21

**Comment by zcraftelite9495** [comment]
Hiya @Domen-1! I have a question, have you ever used Essential Mod before on the client that you are running?

**Comment by zcraftelite9495** [comment]
@IMB11 is the _chosenPresent_ option supposed to be defaulting to -1 when the mod is loaded (In the presets config file)?

**Comment by IMB11** [comment]
It shouldnt be defaulting to -1, remove the `skinshuffle` folder and restart.

**Comment by zcraftelite9495** [comment]
This fails to work, as seen here:
https://mclo.gs/4I0ajPw

**Comment by IMB11** [comment]
SkinShuffle does not work with ViaFabricPlus

**Comment by zcraftelite9495** [comment]
@IMB11 I created a pull request with some proposed changes to the README to include this information. Thanks for your help!
