### ISSUE TITLE
Changes are not saving

### ISSUE THREAD

**Issue by phampyyy** [IMB11/SkinShuffle#120]
### Describe the issue

Changing "Display Widget In Pause Screen" on False (YetAnotherConfigLib does Render thread in game output window something like "Saving SkinShuffleConfig..."). Аfter restart my changes are missing. Pls fix

### SkinShuffle version

2.2.2

**Comment by Lancet-crow** [comment]
I confirm, problem exists, config rebuilds during every enter to game.

**Comment by avilonlegends** [comment]
Can also confirm, this happens to me as well.

**Comment by IMB11** [comment]
I will investigate this, sorry for the wait folks.
