### ISSUE TITLE
Crash when creating skin

### ISSUE THREAD

**Issue by DrBiznes** [IMB11/SkinShuffle#124]
### Describe the issue

When opening the skin menu for the first time no preset exists and pressing the create or select preset button causes the game to crash. I do not have ViaFabricPlus installed.

### SkinShuffle version

2.2.2

### Extra information

[crash-2024-10-21_18.24.09-client.txt](https://github.com/user-attachments/files/17468619/crash-2024-10-21_18.24.09-client.txt)
![2024-10-21_18 24 01](https://github.com/user-attachments/assets/b3274841-7114-4b72-a610-c22c850de514)

**Comment by DrBiznes** [comment]
It seems to be a probelm with getChosenPreset freaking out when the default preset doesn't get generated for some reason. 

I fixed it with

`public static SkinPreset getChosenPreset() {
        if (chosenPreset == null) {
            if (!loadedPresets.isEmpty()) {
                chosenPreset = loadedPresets.get(0);
            } else {
                chosenPreset = SkinPreset.generateDefaultPreset();
                loadedPresets.add(chosenPreset);
            }
            savePresets();
        }
        return chosenPreset;
    }
`
and also some changes to CarouselScreen but the default preset still isn't being created correctly it doesn't have my skin and is named unamed preset for whatever reason so idk but I'll just keep my version for personal use.

**Comment by IMB11** [comment]
Im going to be fixing the preset loader very soon
