### ISSUE TITLE
Crash upon opening Pause menu

### ISSUE THREAD

**Issue by nolight132** [IMB11/SkinShuffle#125]
### Describe the issue

Everything seems to work fine until I try and press Esc to bring up Pause menu. I was unable to investigate the issue using the logs myself, but perhaps they will be of use for you. There are quite a lot of mods though, I can try to minimize the scope of "suspects" if needed, if I have the time. I am getting the same result with v2.2.2 as well. 

### Relevant log output

https://mclo.gs/2UiPosM

### SkinShuffle version

2.2.1

**Comment by dimeetrue** [comment]
+ Today, I faced the same problem.

**Comment by nolight132** [comment]
> * Today, I faced the same problem.

Could you please check if we have any other mods in common? I believe it would help the maintainer to establish what the problem is.
