### ISSUE TITLE
Not working on Neoforge?

### ISSUE THREAD

**Issue by mikhailfluffy** [IMB11/SkinShuffle#129]
### Describe the issue

I tried to change skin, everything works fine, but skin not changing.
Other players and me see my default loaded in minecraft website skin
In singleplayer - the same problem

### Relevant log output

https://mclo.gs/Ji3pGtt

### SkinShuffle version

2.2.2+1.21

### Extra information

I'm using Synitra Connector and FFAPI.

**Comment by IMB11** [comment]
I cannot guarantee my mods work with connector. Report this to connector dev
