### ISSUE TITLE
Game crash after Preset delete

### ISSUE THREAD

**Issue by Lumalee95** [IMB11/SkinShuffle#131]
### Describe the issue

Hello first sorry for my English
So my Problem is. I have deleted my Preset skin now there is nothing in it and i cant create a new one.
Problem is now if the mod is active and i will go to the menu by pressing esc the game crashed.
Now i have turned off the widgets and it will work but the mod is now useless.
Is there a chance to get a new preset to load maybe on client ?
![Bug](https://github.com/user-attachments/assets/18c04d3c-51a9-4642-844d-8d9ff567a674)

### SkinShuffle version

2.2.2+1.21

**Comment by IMB11** [comment]
Please update your mod to 2.3.0
