### ISSUE TITLE
Crash on trying to pause the game without showing the menu (F3+Esc)

### ISSUE THREAD

**Issue by dotPast** [IMB11/SkinShuffle#132]
### Describe the issue

The crash happens on using the F3+Esc hotkey to pause the game without showing the menu. The crash happens in 1.20.1 and 1.21.

This was already reported in issue #49 and fixed in commit 692145f[^1], but the fix was commented out in commit 81d6e54[^2]. Removing the comment fixes the issue in both 1.20.1 and 1.21.

[^1]: https://github.com/IMB11/SkinShuffle/commit/692145f32a300e74366e34e3124a80311642c774#diff-02076c4b42093ff58fef8d3541a5f4335095982480035b0a79272109a009b825R55
[^2]: https://github.com/IMB11/SkinShuffle/commit/81d6e54c711138bb7e867f84d67bf95d470f70ef#diff-02076c4b42093ff58fef8d3541a5f4335095982480035b0a79272109a009b825R55

### Relevant log output

1.20.1: https://mclo.gs/B9347jB; 1.21: https://mclo.gs/ikzCCPY

### SkinShuffle version

2.3.0+1.20.1 and 2.3.0+1.21

**Comment by IMB11** [comment]
Will look into this, no clue why I commented it out, thanks for reporting it!
