### ISSUE TITLE
Configuration is not applied

### ISSUE THREAD

**Issue by seriousfreezing** [IMB11/SkinShuffle#133]
### Describe the issue

I edited the mod configuration via text and then via the interface and neither had any effect

### Relevant log output

https://paste.atlauncher.com/view/86a29a84-387f-4918-b13e-ac7197ff4cf3

### SkinShuffle version

SkinShuffle-2.4.0+1.21

**Comment by IMB11** [comment]
When editing the configuration via the text file, you need to restart the game. Opening the skinshuffle screen when the game is running saves the config.

**Comment by IMB11** [comment]
I see how this might be unintended, I will look into loading every time the config screen is opened.

**Comment by IMB11** [comment]
I think this might be a YACL issue then, because I have everything implemented correctly and i cannot reproduce this issue myself on Windows. Maybe worth making a report on the YACL repo?

**Comment by seriousfreezing** [comment]
I just tested just your mod + Fabric API and I actually managed to reproduce this bug. Do you want me to open an issue in the YACL repo?

**Comment by IMB11** [comment]
Yeah, YACL is packaged with SkinShuffle :+1:
