### ISSUE TITLE
Crash mod

### ISSUE THREAD

**Issue by M1kaX** [IMB11/SkinShuffle#135]
### Describe the issue

When you click on the button to open the skin selection menu, a message appears about saving the world and the game crashes.

### Relevant log
[crash-2024-12-16_00.07.02-client.txt](https://github.com/user-attachments/files/18141147/crash-2024-12-16_00.07.02-client.txt)

_No response_

### SkinShuffle version

2.4.0+1.21

**Comment by IMB11** [comment]
Skinshuffle doesn't use fake world stuff anymore, this should never be possible.

Can you remove your mods 1 by 1 until the issue no longer occurs, would be helpful to figure out which mods you have installed are causing the incompatiblity.

**Comment by M1kaX** [comment]
> Skinshuffle doesn't use fake world stuff anymore, this should never be possible.
> 
> Can you remove your mods 1 by 1 until the issue no longer occurs, would be helpful to figure out which mods you have installed are causing the incompatiblity.

I disabled all mods in my build and left only: SkinShuffle 2.4.0+1.21 and FabricAPI 0.110.0+1.21.1, but the game still crashes when opening the skin selection menu

**Comment by IMB11** [comment]
Can you upload a log of only skinshuffle installed to https://mclo.gs and drop the link here? Thanks

**Comment by M1kaX** [comment]
> Can you upload a log of only skinshuffle installed to https://mclo.gs and drop the link here? Thanks

This is it? https://mclo.gs/ZdKpCep

**Comment by IMB11** [comment]
Please make sure your graphics card drivers are up to date.

**Comment by M1kaX** [comment]
> Please make sure your graphics card drivers are up to date.

I updated my drivers (Nvidia) to the latest version, but the game still crashes

**Comment by IMB11** [comment]
All I can do is recommend you delete the skinshuffle config folder, there's not much I can do I'm afraid as this is a native image crash.

**Comment by M1kaX** [comment]
> All I can do is recommend you delete the skinshuffle config folder, there's not much I can do I'm afraid as this is a native image crash.

Okay, thanks for the help anyway!

**Comment by M1kaX** [comment]
I also found out that the game somehow crashes because of the presets.json file. If you delete it, the game will not crash, but if you return the old data to it, the game will continue to crash.
