### ISSUE TITLE
support skins Ears Mod

### ISSUE THREAD

**Issue by DearFox** [IMB11/SkinShuffle#27]
### Describe your suggestion

in the main menu of the game when you start the game, everything seems to work, but here are the skins that I added to the mod menu, it seems the skins cannot display the ears mod

**Comment by DearFox** [comment]
![image](https://github.com/mineblock11/SkinShuffle/assets/59219907/2f5e05ee-08ed-4e07-a33f-f46a9acd3a35)
Very strange, but now my skin does not want to display Ears mod, although it was displayed on the first launch in the main menu of the game

**Comment by mineblock11** [comment]
We have plans to implement our own cape and ear system that renders optifine and minecraftcapes ears and capes

**Comment by DearFox** [comment]
but I'm talking about something else, I'm talking about this mod https://github.com/unascribed/Ears .  this mod allows you to better customize your minecraft skin.  and partly it worked but only the first time i just installed your mod.

**Comment by DearFox** [comment]
What is most interesting is that if the skin is loaded from a nickname, then everything works as it should in this preview.
So technically it's not hard to get this to work properly with built-in skins.
![image](https://github.com/mineblock11/SkinShuffle/assets/59219907/dd6ef9ef-2411-4b55-92af-8871be6f1e5f)

**Comment by ssterling** [comment]
I just experienced the same problem.  I hope that @mineblock11 re-opens this issue; I don’t want to have to change to another skin-swap mod *again*.

I’d like to add that the carousel also displays the skin without Ears additions, and that the username grabber is the only source where my Ears-enabled skin renders correctly.

![2023-08-10_15 03 45](https://github.com/mineblock11/SkinShuffle/assets/25623635/1bb04c3b-1a01-4872-8f12-3f0ebbcb3d2f)

**Comment by Spelint** [comment]
I want to see ears mod support!
