### ISSUE TITLE
Not compatible with Create?

### ISSUE THREAD

**Issue by olivrrs** [IMB11/SkinShuffle#59]
### Describe the issue

When trying to open the skins menu with Create Fabric installed, the game crashes.
The version of Create I had was 0.5.1

### SkinShuffle version

1.0.1 + 1.20

**Comment by zOnlyKroks** [comment]
A crash log or latest log would be helpful to see what is going on there

**Comment by olivrrs** [comment]
[2024-01-22-1.log.gz](https://github.com/IMB11/SkinShuffle/files/14042757/2024-01-22-1.log.gz)
This should be the correct log, sorry for the delay.

**Comment by Liamgrayskull** [comment]
Same error happened on my end 
[crash-2024-01-24_16.48.20-client.txt](https://github.com/IMB11/SkinShuffle/files/14045379/crash-2024-01-24_16.48.20-client.txt)

**Comment by rinyafii** [comment]
I have the same crash, using 1.20.1. 
https://mclo.gs/CqOcGrH

**Comment by IMB11** [comment]
Seems like an issue with porting lib. Will investigate

**Comment by Aulberon** [comment]
When using SkinShuffle 1.1 the game doesn't open. This is is the latest.log:
https://gist.github.com/Aulberon/b794cfe991bd4fd2527efad2f467ad8f#file-latest-log-1-1

When using SkinShuffle 1.0.1 the game starts but there's no character widget and when we try to enter the skin menu, the game crashes. This is the latest.log:
https://gist.github.com/Aulberon/b794cfe991bd4fd2527efad2f467ad8f#file-latest-log-1-0-1

**Comment by IMB11** [comment]
Fixed in 2.0.0, will be out soon, stay updated in my discord https://discord.imb11.dev/
