### ISSUE TITLE
Crash with mods

### ISSUE THREAD

**Issue by exd1337** [IMB11/SkinShuffle#60]
### Describe the issue

When opening minecraft, it crashes with skin shuffle

### Relevant log output

https://mclo.gs/AHOdtfM

### SkinShuffle version

1.0.1

**Comment by shizotoaster** [comment]
You're using legacy launcher which patches authlib in order to support ely.by skins. You either need to use your Microsoft account to play Minecraft or disable ely.by in launcher settings

This is not a skin shuffle bug and has to be fixed on ely.by side

**Comment by IMB11** [comment]
SkinShuffle does not support piracy.
