### ISSUE TITLE
Strange skin rendering

### ISSUE THREAD

**Issue by skycatminepokie** [IMB11/SkinShuffle#61]
### Describe the issue

My skin seems to render in a strange way. I've noticed this appearance before with other mods (forge 1.8.9, likely Essential or OptiFine causing it), but this is the first time in a long time. Below is how my skin normally renders (and usually renders in-game): 
![image](https://github.com/IMB11/SkinShuffle/assets/52087591/f8657727-00c4-471b-b119-de1dfcb2e4e2)

The SkinShuffle preview renders it like this:
![image](https://github.com/IMB11/SkinShuffle/assets/52087591/63511315-f3ff-4a10-b4b3-6e5cb6bbbf68)
It also occasionally renders like this in-game, but only with this mod installed. My friends (playing without the mod, server has the mod) haven't seen the bugged rendering on their side before.

Not sure what the edge case is - maybe it's something that I need to fix with my skin, but the skin is very old. I'm fairly certain I'm using the right player model (classic)

### Relevant log output

https://mclo.gs/I6zfJ3G

### SkinShuffle version

1.0.1+1.20

### Extra information

Default configs.

**Comment by IMB11** [comment]
It's because your skin is in the old 1.8 skin format, yes it'll work on your skin, but for some reason it breaks the skinshuffle preview renderer, and we dont know why.

**Comment by IMB11** [comment]
Seems to be fixed, unless you updated your skin to the modern skin format;
![image](https://github.com/IMB11/SkinShuffle/assets/93472213/f460ea85-11bb-4435-b158-4000aaa6899c)
