### ISSUE TITLE
Skins duplicate

### ISSUE THREAD

**Issue by CoBehOKjar** [IMB11/SkinShuffle#62]
### Describe the issue

With each new opening of the menu, the skins were duplicated and saved to a file. After restarting, when trying to open the skins menu, the game crashed. I had to manually clean the file
This never happened again

### Relevant log output

crash - https://mclo.gs/uv2CCtT , before reboot - https://mclo.gs/llcOE3W

### SkinShuffle version

1.0.1+1.20

### Extra information

[config.json](https://github.com/IMB11/SkinShuffle/files/14535191/config.json)
[Bug Report](https://youtu.be/VxnVnWjyTEA)

**Comment by IMB11** [comment]
Please ensure you have the latest version of skinshuffle.

**Comment by IMB11** [comment]
This is fixed in 1.1.0 - I'd advise you to update.

**Comment by CoBehOKjar** [comment]
ok, thanks
