### ISSUE TITLE
Skins upload with slim model

### ISSUE THREAD

**Issue by mpar-22** [IMB11/SkinShuffle#63]
### Describe the issue

When changing skins in-game, skins upload using the slim model even if it's set to be a classic model. On the client end, the skin will show as a classic model at first, but when reconnecting to the server, it will show as the slim model. Additionally, the skin appears as the slim model in the Minecraft launcher, indicating the file is being uploaded to Mojang's servers as the slim model.

### Relevant log output

https://mclo.gs/amTm7Lk

### SkinShuffle version

1.1.0+1.20.4

### Extra information

[Video demonstrating the bug](https://youtu.be/VMd4QAUmpxo)

**Comment by DerpDerpling** [comment]
i am also experiencing this issue

**Comment by Luadih** [comment]
This seems to still happen currently. Though I tried while in the main menu, after cleaning the config folder and it seemed to work fine while checking the minecraft page to see if the correct body type was getting uploaded. After a restart of Minecraft it stopped working as it should, and uploaded all of my presets as slim (which btw none are)

**Comment by IMB11** [comment]
Fixed in 2.0.0
