### ISSUE TITLE
How i can change skin by File or Resourse Location?

### ISSUE THREAD

**Issue by Rabwplen** [IMB11/SkinShuffle#72]
### Describe your suggestion

i dont understand how to do it
![зображення_2024-05-18_194244566](https://github.com/IMB11/SkinShuffle/assets/170195476/52b318c0-c1f8-4c8d-85b0-a972bf08832b)

**Comment by Squiredarksbane** [comment]
What you need to do is go to the actual png, like the downloads folder and then copy the png as path
So it will be something like: C:\Users\[username]\Downloads\[name of skin].png
This is for the file setting
