### ISSUE TITLE
Incompatible with Create

### ISSUE THREAD

**Issue by NovaPride** [IMB11/SkinShuffle#76]
### Describe the issue

Crashes when you click on "Skin Presets" button. Also not showed paper doll. I have checked all create-fabric and few skin shuffle versions for 1.20.1, all have that crash. 
![image](https://github.com/IMB11/SkinShuffle/assets/36445286/7324a10d-00ee-4210-8ec8-bf1d32b0d33e) 

### Relevant log output

https://mclo.gs/YTYg8EI

### SkinShuffle version

SkinShuffle 1.0.1+1.20

**Comment by IMB11** [comment]
Update porting lib or install latest porting lib.

**Comment by IMB11** [comment]
Actually, update your skinshuffle to 2.0.0

**Comment by IMB11** [comment]
Update SkinShuffle to 2.0.0, this is fixed in 2.0.0

The 1.20.1 version works fine on 1.20

**Comment by IMB11** [comment]
@NovaPride If it doesn't work on SkinShuffle 2.0.0, pleasr put the log here. If it does, close the issue.
