### ISSUE TITLE
Crash when clicking Skin Presets button

### ISSUE THREAD

**Issue by Aulberon** [IMB11/SkinShuffle#78]
### Describe the issue

Crash when clicking Skin Presets button

### Relevant log output

https://gist.github.com/Aulberon/5fb32de069a5a639b1a331c53e82ca47

### SkinShuffle version

SkinShuffle 2.0.2+1.20.1

**Comment by IMB11** [comment]
You are using Connector, any bugs or crashes you encounter are at your own risk.
