### ISSUE TITLE
1.21 Crash on latest 2.0.2 version 

### ISSUE THREAD

**Issue by yichifauzi** [IMB11/SkinShuffle#80]
### Describe the issue

when using these mods below crash on start

 fabric-api-0.100.4+1.21
 modmenu-11.0.1
 placeholder-api-2.4.0+1.21
 SkinShuffle-2.0.2+1.21

### Relevant log output

https://mclo.gs/GMUXiDK

### SkinShuffle version

2.0.2

**Comment by yichifauzi** [comment]
nevermind just start again it fixed lol

**Comment by yichifauzi** [comment]
https://mclo.gs/N8Fa8qW
Oooopss crash again when click skin preset

**Comment by IMB11** [comment]
NativeImage strikes again ugh - will investigate.

**Comment by IMB11** [comment]
Going to merge this into one big issue.

Duplicate of #86
