### ISSUE TITLE
SkinShuffle and Essential conflict

### ISSUE THREAD

**Issue by EngurRuzgar** [IMB11/SkinShuffle#81]
### Describe the issue

So I have both Essential and SkinShuffle which ends up displaying 2 characters in the main menu, but the problem is if I exit SkinShuffle menu after entering from the menu, the game crashes.

There was no problem in 1.20.1 with these mods.

### Relevant log output

https://mclo.gs/ONXkxhy Crash report
https://mclo.gs/lAoxU1y latest.log

### SkinShuffle version

Latest on CurseForge 1.21

**Comment by IMB11** [comment]
Well obviously this isn't going to get fixed, Essentials is bloatware, there are plenty other community-made mods that complete the many different features that essentials provides:

Cosmetics: figura, ETF, ETM
Skins: SkinShuffle, Fabric Tailor
Multiplayer: e4mc, World Host, P2P
Messaging: Discord, Whatsapp, SMS lol
