### ISSUE TITLE
Incompatible with Wildfire's Female Gender mod

### ISSUE THREAD

**Issue by arcade-smasher** [IMB11/SkinShuffle#83]
### Describe the issue

The game crashes with [Wildfire's Female Gender mod](https://modrinth.com/mod/female-gender) once the progress bar with the Mojang logo on a red background reaches 100%, or, in other words when the first frame of the game renders. SkinShuffle and Wildfire's Female Gender mod are the only two mods installed.

### Relevant log output

https://mclo.gs/yNcEKDa

### SkinShuffle version

2.0.2+1.20.1

### Extra information

https://github.com/IMB11/SkinShuffle/assets/83091369/2348a91f-7a5b-48ee-8e6f-06997ce46e6a

**Comment by IMB11** [comment]
Duplicate of #82
