### ISSUE TITLE
Preview Rendering Style option doesn't work

### ISSUE THREAD

**Issue by mpar-22** [IMB11/SkinShuffle#84]
### Describe the issue

The Preview Rendering Style option is seemingly ignored, as changing it doesn't change how the skin renders in the edit menu. Instead, the edit menu preview seems to be tied to the Carousel Rendering Style option.

### Relevant log output

https://mclo.gs/yMSoEhd

### SkinShuffle version

2.0.3+1.21

**Comment by IMB11** [comment]
Not really sure what you mean, can you upload a video?

**Comment by mpar-22** [comment]
Yes, here you go. As you can see, the editing pane takes the rendering style option from the carousel rendering type option, not preview.

https://github.com/IMB11/SkinShuffle/assets/95056585/c586b575-cf8a-46af-bdf9-c4dfb06831bb

**Comment by IMB11** [comment]
But you set both preview and carousel to the same values for this entire video?

**Comment by IMB11** [comment]
Oh, i mis-read the config value. I see, will investigate
