### ISSUE TITLE
Crash when click "Cancel"

### ISSUE THREAD

**Issue by IntMarco** [IMB11/SkinShuffle#85]
### Describe the issue

The game crashes when u click "Cancel".

Step to reproduce:
- Open Minecraft
- Open Skinshuffle GUI
- Click "Cancel"
- CRASH 💥

### Relevant log output

https://mclo.gs/YK0E1fO

### SkinShuffle version

2.0.3 (1.21)

### Extra information

Only happens in a "Fresh start" (first startup of Minecraft)

**Comment by IMB11** [comment]
Please perform a binary search to find the mod causing the crash, remove mods one by one until the SkinShuffle crash no longer occurs, then report here which mod is incompatible.

**Comment by IMB11** [comment]
I've managed to reproduce this, will put out a fix in the next update.
