### ISSUE TITLE
Incompatible with fresh moves

### ISSUE THREAD

**Issue by Crappy-Productions** [IMB11/SkinShuffle#87]
### Describe the issue

Fresh moves (https://modrinth.com/resourcepack/tras-fresh-player) adds eye animations to the player's skin and it's broken in the skin shuffle's preview.

### SkinShuffle version

2.0.4+1.21

### Extra information

How it looks in preview:
![Screenshot 2024-07-13 085317](https://github.com/user-attachments/assets/dadaa5fe-b147-4f3c-9687-f5c8a2543d92)
How it should look:
![image](https://github.com/user-attachments/assets/a2971f63-169a-4c9e-b5c7-910d308dd68e)

**Comment by IMB11** [comment]
Should be fixed with 2.2.0's release. Please re-open if you still encounter this after 2.2.0 releases.

**Comment by Crappy-Productions** [comment]
:0
thx

**Comment by Crappy-Productions** [comment]
yea from what I've heard Fresh Moves is the issue
