### ISSUE TITLE
Skin Preset button crashes my game

### ISSUE THREAD

**Issue by easya7** [IMB11/SkinShuffle#93]
### Describe the issue

I don't why but whenever I click the skin preset button it just crashes my game.

### SkinShuffle version

1.21

**Comment by IMB11** [comment]
Please upload your logs to mclo.gs, or I cannot help you.

**Comment by aelooney** [comment]
I have the same problem with my modpack, do you know why that could be?
https://mclo.gs/GF5W3bq

**Comment by TIle7** [comment]
Same here. I uploaded a skin which is visible on the main screen but not in game when I press E.
And then when I try to do something about it, just pressing skin preset crashes the game.
Minecraft 1.21, Fabris 1.21, Mod version from 9th of July.

https://mclo.gs/k8Pxc1h

**Comment by seriousfreezing** [comment]
Mine also crashes.
[crash-2024-08-03_18.08.01-client.txt](https://github.com/user-attachments/files/16482914/crash-2024-08-03_18.08.01-client.txt)

**Comment by danielL212** [comment]
it crashes for me too also i uploaded a skin that shows in the main screen but its not visible in the game (https://mclo.gs/k6mY4s3)

**Comment by IMB11** [comment]
Might be fixed in next update, let me know if its not.
