### ISSUE TITLE
Unix File Location Support???

### ISSUE THREAD

**Issue by RobotZGalaxy** [IMB11/SkinShuffle#95]
### Describe your suggestion

As it functions on my end, using file locations doesn't function for me. My assumption as it works perfectly otherwise, is that Unix systems (using Linux Mint) aren't supported as of now. Would be great if I could use the feature properly as the workaround I have figured out is less than ideal.

**Comment by IMB11** [comment]
Can you provide me with your logs please @RobotZGalaxy ?

**Comment by IMB11** [comment]
https://mclo.gs/

**Comment by IMB11** [comment]
I have found that copying files on linux using a file manager/explorer results in a `copyfile://` URL being created, 
eg: `x-special/nautilus-clipboard
copy
file:///home/calum/Desktop/hunter.png
`

Make sure your file path does not contain a copy-file::// prefix

**Comment by RobotZGalaxy** [comment]
> I have found that copying files on linux using a file manager/explorer results in a `copyfile://` URL being created, eg: `x-special/nautilus-clipboard copy file:///home/calum/Desktop/hunter.png `
> 
> Make sure your file path does not contain a copy-file::// prefix

The prefix was not there. The name of the file is StreetwearGalaxy (2024_03_09 07_53_11 UTC).png; I transferred it from another computer and the extension automatically added itself. I've tried removing it and it made no difference.

>provide me with your logs

https://mclo.gs/ivXgwy9

**Comment by IMB11** [comment]
You need to put in the full path, not just the file name.

**Comment by IMB11** [comment]
eg : /home/username/Desktop/Streetware Galaxy(...).png

**Comment by RobotZGalaxy** [comment]
> eg : /home/username/Desktop/Streetware Galaxy(...).png
I did, I was just putting the filename in case if the underscores was causing the problem or something

**Comment by JaguarProJoe** [comment]
The logs suggest you are using the flatpak version of prism launcher, maybe try granting file permissions through flatseal so that minecraft can access the location you want it to
Either that or copy the png into the minecraft directory and point to it there

**Comment by IMB11** [comment]
Actually, that would explain why I myself am encountering this issue in production but not in dev, I use prism launcher to test. Granting file permissions seemed to have fixed it. Closing.

**Comment by IMB11** [comment]
**WORKAROUND: Grant Prism Launcher File Permissions**

**Comment by RobotZGalaxy** [comment]
> Actually, that would explain why I myself am encountering this issue in production but not in dev, I use prism launcher to test. Granting file permissions seemed to have fixed it. Closing.

Yep that did it!! Makes sense in hindsight
